micronaut:
  application:
    name: apiCrud
datasources:
  default:
    driver-class-name: oracle.jdbc.OracleDriver
    db-type: oracle
    dialect: ORACLE
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
